[student@workstation data-review]$ cat playbook.yml 
---

- name: Playbook
  hosts: webserver
  vars_files:
    - vars/secret.yml
  vars: 
    firewall_pkg: firewalld
    web_pkg: httpd
    web_svc: httpd
    ssl_pkg: mod_ssl
    python_pkg: python-passlib
    httpdconf_src: files/httpd.conf
    httpdconf_file: /etc/httpd/conf/httpd.conf
    htaccess_srv: files/.htaccess
    secrets_dir: /etc/httpd/secrets
    secrets_file: "{{ secrets_dir }}/htpasswd }}"
    web_root: /var/www/html
    web_user: guest 
  tasks: 
    - name: Verify firewall_pkg
      yum: 
        name: 
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
          - "{{ python_pkg }}"
        state: latest
    - name : Ensure the file is copied
      copy: 
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_file }}"
        owner: root
        group: root
        mode: 0644
    - name: create directory
      file:
        path: "{{ secrets_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: 0500
    - name: create an htpasswd file to be used for basic authent 
      htpasswd: 
        path: "{{ secrets_file }}"
        name: "{{ web_user }} "
        password: "{{ web_pass }}" 
        owner: apache
        group: apache
        mode: 0400
    - name: create the htaccess
      copy: 
        src: "{{ htaccess_srv }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400
    - name: copy module index.html
      copy: 
        content: "{{ ansible_facts['fqdn'] }} ({{ansible_facts['default_ipv4']['address'] }}) has been customized by Ansible. \n"
        dest: "{{web_root }}/index.html }}" 
        owner: 
    - name: Open the port  for the webserver
      firewalld: 
        service: https
        state: enabled
        immediate: true
        permanent: true
    - name: 
      service:
        name: firewalld
        state: restarted
        enabled: true
